services:
  taubi-db:
    image: yobasystems/alpine-mariadb:latest
    container_name: taubi-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    networks:
      taubi-network:
        ipv4_address: 192.168.5.2
    volumes:
      - taubi-db-storage:/var/lib/mysql

  taubi-srv:
    image: php:apache
    container_name: taubi-srv
    restart: unless-stopped
    networks:
      taubi-network:
        ipv4_address: 192.168.5.3
    ports:
       - "80:80"
    depends_on:
      - taubi-db
    volumes:
      - ./app-code:/var/www/html
networks:
  taubi-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.5.0/24

volumes:
  taubi-db-storage:
    external: true
