services:
  taubi-db:
    image: yobasystems/alpine-mariadb:latest
    container_name: taubi-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    networks:
      taubi-network:
        ipv4_address: 192.168.6.2
    volumes:
      - taubi-db-storage:/var/lib/mysql

  taubi-srv:
    build:
      context: .
      dockerfile: srv_dockerfile
    container_name: taubi-srv
    restart: unless-stopped
    networks:
      taubi-network:
        ipv4_address: 192.168.6.3
    ports:
       - "450:80"
    depends_on:
      - taubi-db
    volumes:
      - ./apache-conf:/etc/apache2/sites-available
      - ./php-conf:/usr/local/etc/php/
      - ./app-code:/var/www/html
      - ./app-code/api/bookcovers:/var/www/html/bookcovers
    command: /bin/sh -c "chmod -R 777 /var/www/html/bookcovers && apache2-foreground"
networks:
  taubi-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.6.0/24

volumes:
  taubi-db-storage:
    external: true
